"use strict";
exports.__esModule = true;
var ProductService_1 = require("./ProductService");
var Product_1 = require("./Product");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getProducts();
var p = new Product_1.Product();
p.name = "Iphone 14";
p.category = "Phone";
p.price = 30000;
_productService.saveProduct(p);
console.log(result);
